export const metroLines = {
  1: {
    name: "Métro Ligne 1",
    type: "metro",
    description:
      "La ligne 1 du métro parisien est la plus ancienne et la plus fréquentée, reliant La Défense à Château de Vincennes. Elle dessert 25 stations sur une distance de 16,5 km. Elle est automatique depuis 2012, ce qui permet une fréquence élevée et une meilleure régularité.",
    stations: [
      "La Défense",
      "Esplanade de La Défense",
      "Pont de Neuilly",
      "Les Sablons",
      "Porte Maillot",
      "Argentine",
      "Charles de Gaulle - Étoile",
      "George V",
      "Franklin D. Roosevelt",
      "Champs-Élysées - Clemenceau",
      "Concorde",
      "Tuileries",
      "Palais Royal - Musée du Louvre",
      "Louvre - Rivoli",
      "Châtelet",
      "Hôtel de Ville",
      "Saint-Paul",
      "Bastille",
      "Gare de Lyon",
      "Reuilly - Diderot",
      "Nation",
      "Porte de Vincennes",
      "Saint-Mandé",
      "Bérault",
      "Château de Vincennes"
    ],
  },
  2: {
    name: "Métro Ligne 2",
    type: "metro",
    description: "La ligne 2 est l’une des plus anciennes et les plus exploitées pour la mobilité des Franciliens. Cette ligne est semi-circulaire, tout comme la ligne 6, mais est au Nord de la ville, et est longue de 12.4 km.",
    stations: [
        "Alexandre Dumas",
        "Anvers",
        "Barbès Rochechouart",
        "Belleville",
        "Blanche",
        "Buzenval / Avron",
        "Charles-de-Gaulle Étoile",
        "Colonel Fabien",
        "Courcelles",
        "Couronnes",
        "Jaurès",
        "La Chapelle",
        "Monceau",
        "Ménilmontant",
        "Nation",
        "Philippe Auguste",
        "Pigalle",
        "Place de Clichy",
        "Porte Dauphine",
        "Père Lachaise",
        "Rome",
        "Stalingrad",
        "Ternes",
        "Victor Hugo",
        "Villiers"

    ],
  },
  3: {
    name: "Métro Ligne 3",
    type: "metro",
    description: "La ligne 3 relie Pont de Levallois - Bécon à Gallieni. Longue de 11,7 km, elle traverse Paris d'ouest en est avec 25 stations, desservant des sites comme Opéra ou République.",
    stations: [
      "Anatole France",
      "Arts et Métiers",
      "Bourse",
      "Europe",
      "Gallieni",
      "Gambetta",
      "Louise Michel",
      "Malesherbes",
      "Opéra",
      "Parmentier",
      "Pereire",
      "Père Lachaise",
      "Pont de Levallois - Bécon",
      "Porte de Bagnolet",
      "Porte de Champerret",
      "Quatre-Septembre",
      "République",
      "Réaumur - Sébastopol",
      "Rue Saint-Maur",
      "Saint-Lazare",
      "Sentier",
      "Temple",
      "Villiers",
      "Wagram"
    ],
  },

  "3bis": {
    name: "Métro Ligne 3bis",
    type: "metro",
    description: "Ancien tronçon de la ligne 3, cette courte ligne de 1,3 km relie Gambetta à Porte des Lilas avec 4 stations, principalement en souterrain.",
    stations: [
      "Gambetta",
      "Pelleport",
      "Porte des Lilas",
      "Saint-Fargeau"
    ],
  },  
  4: {
    name: "Métro Ligne 4",
    type: "metro",
    description:
      "La ligne 4 du métro parisien traverse la capitale du nord au sud. Elle relie Porte de Clignancourt à Mairie de Montrouge, avec 27 stations. Elle est en cours de modernisation et automatisation partielle.",
    stations: [
      "Porte de Clignancourt",
      "Marcadet - Poissonniers",
      "Simplon",
      "Château Rouge",
      "Barbès - Rochechouart",
      "Gare du Nord",
      "Gare de l'Est",
      "Château d'Eau",
      "Strasbourg - Saint-Denis",
      "Réaumur - Sébastopol",
      "Étienne Marcel",
      "Les Halles",
      "Cité",
      "Saint-Michel",
      "Odéon",
      "Saint-Germain-des-Prés",
      "Saint-Sulpice",
      "Montparnasse - Bienvenüe",
      "Vavin",
      "Raspail",
      "Denfert-Rochereau",
      "Mouton-Duvernet",
      "Alésia",
      "Porte d'Orléans",
      "Mairie de Montrouge"
    ],
  },
  5: {
    name: "Métro Ligne 5",
    type: "metro",
    description: "La ligne 5 relie Place d'Italie à Bobigny - Pablo Picasso. Longue de 14,6 km avec 22 stations, elle dessert le nord-est parisien et la banlieue Bobigny.",
    stations: [
      "Bobigny - Pablo Picasso",
      "Bobigny - Pantin - Raymond Queneau",
      "Campo Formio",
      "Gare d'Austerlitz",
      "Gare de l'Est",
      "Gare du Nord",
      "Hoche",
      "Jacques Bonsergent",
      "Jaurès",
      "Laumière",
      "Oberkampf",
      "Place d'Italie",
      "Porte de Pantin",
      "Quai de la Rapée",
      "République",
      "Richard-Lenoir",
      "Saint-Marcel",
      "Stalingrad",
      "Église de Pantin"
    ],
  },
  6: {
    name: "Métro Ligne 6",
    type: "metro",
    description: "La ligne 6 du métro parisien relie Charles de Gaulle - Étoile à Nation. Longue de 13,6 km, elle dessert 28 stations et transporte environ 500 000 voyageurs par jour. C'est la 7e ligne la plus fréquentée du réseau.",
    stations: [
      "Bel-Air",
      "Bir-Hakeim",
      "Boissière",
      "Cambronne",
      "Charles-de-Gaulle Étoile",
      "Chevaleret",
      "Corvisart",
      "Daumesnil",
      "Denfert Rochereau",
      "Dugommier",
      "Dupleix",
      "Edgar Quinet",
      "Gare Montparnasse",
      "Gare de Bercy",
      "Glacière",
      "Kléber",
      "La Motte Picquet - Grenelle",
      "Nation",
      "Nationale",
      "Passy",
      "Pasteur",
      "Picpus",
      "Place d'Italie - Italie 2",
      "Quai de la Gare",
      "Raspail",
      "Saint-Jacques",
      "Sèvres Lecourbe",
      "Trocadéro"
    ],
  },

  7: {
    name: "Métro Ligne 7",
    type: "metro",
    description: "La ligne 7 relie La Courneuve à Villejuif/Mairie d'Ivry avec deux branches sud. Longue de 22,5 km, elle dessert 38 stations et traverse Paris du nord-est au sud-est en passant par le centre-ville.",
    stations: [
      "Aubervilliers Pantin Quatre Chemins",
      "Cadet",
      "Censier Daubenton",
      "Chaussée d'Antin - La Fayette",
      "Château Landon",
      "Châtelet",
      "Corentin Cariou",
      "Crimée",
      "Fort d'Aubervilliers",
      "Gare de l'Est",
      "Jussieu",
      "La Courneuve - 8 Mai 1945",
      "Le Kremlin - Bicêtre",
      "Le Peletier",
      "Les Gobelins",
      "Louis Blanc",
      "Mairie d'Ivry",
      "Maison Blanche",
      "Opéra",
      "Palais Royal - Musée Du Louvre",
      "Paul Vaillant Couturier",
      "Pierre et Marie Curie",
      "Place Monge",
      "Place d'Italie - Italie 2",
      "Poissonnière",
      "Pont Marie (Cité des Arts)",
      "Pont Neuf",
      "Porte d'Italie",
      "Porte d'Ivry",
      "Porte de Choisy",
      "Porte de La Villette",
      "Pyramides",
      "Riquet",
      "Souppes - Château-Landon",
      "Stalingrad",
      "Sully Morland",
      "Tolbiac",
      "Villejuif Louis Aragon",
      "Villejuif Léo Lagrange"
    ],
  },
  8: {
    name: "Métro Ligne 8",
    type: "metro",
    description: "La ligne 8 relie Balard à Pointe du Lac. Longue de 23,4 km avec 38 stations, elle traverse Paris du sud-ouest au sud-est en suivant la Seine.",
    stations: [
      "Balard",
      "Boucicaut",
      "Chevaleret",
      "Commerce",
      "Concorde",
      "Daumesnil",
      "École Militaire",
      "Félix Faure",
      "Grands Boulevards",
      "Invalides",
      "La Motte-Picquet - Grenelle",
      "La Tour-Maubourg",
      "Lamarck - Caulaincourt",
      "Lourmel",
      "Madeleine",
      "Maisons-Alfort - Les Juilliottes",
      "Maisons-Alfort - Stade",
      "Michel Bizot",
      "Montgallet",
      "Opéra",
      "Pointe du Lac",
      "Porte de Charenton",
      "Porte Dorée",
      "Porte de Montreuil",
      "Reuilly - Diderot",
      "Richelieu - Drouot",
      "Saint-Sébastien - Froissart",
      "Ségur",
      "Tolbiac"
    ],
  },

  9: {
    name: "Métro Ligne 9",
    type: "metro",
    description: "La ligne 9 relie Pont de Sèvres à Mairie de Montreuil. Longue de 19,6 km avec 37 stations, c'est une ligne est-ouest majeure traversant Paris.",
    stations: [
      "Alma - Marceau",
      "Buzenval",
      "Charonne",
      "Exelmans",
      "Iéna",
      "Jasmin",
      "Mairie de Montreuil",
      "Maraîchers",
      "Michel-Ange - Auteuil",
      "Michel-Ange - Molitor",
      "Nation",
      "Porte de Saint-Cloud",
      "Robespierre",
      "Rue des Boulets",
      "Saint-Ambroise",
      "Saint-Augustin",
      "Saint-Fargeau",
      "Saint-Philippe du Roule",
      "Sèvres - Babylone",
      "Trocadéro",
      "Voltaire"
    ],
  },

  10: {
    name: "Métro Ligne 10",
    type: "metro",
    description: "La ligne 10 relie Boulogne - Pont de Saint-Cloud à Gare d'Austerlitz. Cette ligne en forme de U de 11,7 km dessert 23 stations, principalement dans le sud parisien.",
    stations: [
      "Boulogne - Jean Jaurès",
      "Boulogne - Pont de Saint-Cloud",
      "Cardinal Lemoine",
      "Chardon-Lagache",
      "Cluny - La Sorbonne",
      "Duroc",
      "Église d'Auteuil",
      "Gare d'Austerlitz",
      "Javel - André Citroën",
      "La Motte-Picquet - Grenelle",
      "Mabillon",
      "Michel-Ange - Molitor",
      "Mirabeau",
      "Odéon",
      "Porte d'Auteuil",
      "Ségur",
      "Sèvres - Babylone",
      "Vaneau"
    ],
  },

  11: {
    name: "Métro Ligne 11",
    type: "metro",
    description: "La ligne 11 relie Châtelet à Mairie des Lilas. Courte (6,3 km) avec 13 stations, c'est l'une des rares lignes nord-est/sud-est entièrement automatiques.",
    stations: [
      "Belleville",
      "Châtelet",
      "Goncourt",
      "Hôtel de Ville",
      "Jourdain",
      "Mairie des Lilas",
      "Palais Royal - Musée du Louvre",
      "Porte des Lilas",
      "Rambuteau",
      "République",
      "Télégraphe",
      "Arts et Métiers"
    ],
  },
  11: {
    name: "Métro Ligne 11",
    type: "metro",
    description: "La ligne 11 relie Châtelet à Mairie des Lilas. Courte (6,3 km) avec 13 stations, c'est l'une des rares lignes nord-est/sud-est entièrement automatiques.",
    stations: [
      "Belleville",
      "Châtelet",
      "Goncourt",
      "Hôtel de Ville",
      "Jourdain",
      "Mairie des Lilas",
      "Palais Royal - Musée du Louvre",
      "Porte des Lilas",
      "Rambuteau",
      "République",
      "Télégraphe",
      "Arts et Métiers"
    ],
  },
  12: {
    name: "Métro Ligne 12",
    type: "metro",
    description: "La ligne 12 relie Mairie d'Aubervilliers à Mairie d'Issy sur 17 km. Inaugurée en 1910, c'est l'une des lignes les plus longues avec 31 stations, traversant Paris du nord-est au sud-ouest.",
    stations: [
      "Abbesses",
      "Aimé Césaire",
      "Assemblée Nationale / Lille - Université",
      "Concorde",
      "Convention",
      "Corentin Celton",
      "Falguière",
      "Front Populaire",
      "Gare Montparnasse",
      "Gare Saint-Lazare",
      "Jules Joffrin",
      "Lamarck Caulaincourt",
      "Madeleine",
      "Mairie d'Aubervilliers",
      "Mairie d'Issy",
      "Marcadet Poissonniers",
      "Marx Dormoy",
      "Notre-Dame-de-Lorette",
      "Notre-Dame-des-Champs",
      "Pasteur",
      "Pigalle",
      "Porte de La Chapelle",
      "Porte de Versailles",
      "Rennes",
      "Rue du Bac",
      "Saint-Georges",
      "Solférino",
      "Sèvres Babylone",
      "Trinité d'Estienne d'Orves",
      "Vaugirard",
      "Volontaires"
    ],
  },
  13: {
    name: "Métro Ligne 13",
    type: "metro",
    description: "La ligne 13 relie Saint-Denis - Université/Asnières-Gennevilliers à Châtillon - Montrouge. Longue de 24,3 km (la plus longue du réseau), elle dessert 32 stations avec deux branches nord.",
    stations: [
      "Asnières - Gennevilliers - Les Courtilles",
      "Basilique de Saint-Denis",
      "Brochant",
      "Carrefour Pleyel",
      "Châtillon - Montrouge",
      "Gabriel Péri",
      "Garibaldi",
      "La Fourche",
      "Liège",
      "Malakoff - Plateau de Vanves",
      "Mairie de Clichy",
      "Montparnasse - Bienvenüe",
      "Porte de Clichy",
      "Saint-Denis - Porte de Paris",
      "Saint-Denis - Université",
      "Saint-Lazare",
      "Vanves - Malakoff"
    ],
  },
  14: {
    name: "Métro Ligne 14",
    type: "metro",
    description: "Ligne automatique reliant Saint-Ouen à Olympiades. Longue de 14 km avec 13 stations, c'est la ligne la plus moderne avec des trains sans conducteur.",
    stations: [
      "Bibliothèque François Mitterrand",
      "Châtelet",
      "Cour Saint-Émilion",
      "Gare de Lyon",
      "Madeleine",
      "Olympiades",
      "Pyramides",
      "Saint-Lazare",
      "Saint-Ouen"
    ],
  },
};

export const rerLines = {
  A: {
    name: "RER A",
    type: "rer",
    description:
      "Le RER A est la ligne la plus fréquentée du réseau RER en Île-de-France, reliant l'est à l'ouest en passant par le centre de Paris. Elle dessert 46 stations sur environ 108 km, réparties en plusieurs branches. La fréquence est élevée, surtout en heures de pointe.",
    stations: [
      "Saint-Germain-en-Laye",
      "Le Vésinet - Le Pecq",
      "Le Vésinet - Centre",
      "Chatou - Croissy",
      "Rueil-Malmaison",
      "Nanterre - Ville",
      "Nanterre - Préfecture",
      "La Défense",
      "Charles de Gaulle - Étoile",
      "Auber",
      "Châtelet - Les Halles",
      "Gare de Lyon",
      "Nation",
      "Vincennes",
      "Fontenay-sous-Bois",
      "Nogent-sur-Marne",
      "Joinville-le-Pont",
      "Saint-Maur - Créteil",
      "La Varenne - Chennevières",
      "Sucy - Bonneuil",
      "Boissy-Saint-Léger"
    ],
  },
  B: {
    name: "RER B",
    type: "rer",
    description:
      "La ligne B du RER traverse la région Île-de-France du nord au sud, reliant l'aéroport Charles-de-Gaulle au sud de Paris et la ville de Robinson au sud-ouest. Elle dessert 47 stations avec une forte fréquentation, notamment aux heures de pointe.",
    stations: [
      "Aéroport Charles de Gaulle 2",
      "Aéroport Charles de Gaulle 1",
      "Mitry-Claye",
      "Villeparisis - Mitry-le-Neuf",
      "Sevran - Beaudottes",
      "Aulnay-sous-Bois",
      "Le Blanc-Mesnil",
      "Drancy",
      "Le Bourget",
      "La Plaine - Stade de France",
      "Stade de France - Saint-Denis",
      "Gare du Nord",
      "Châtelet - Les Halles",
      "Luxembourg",
      "Port-Royal",
      "Denfert-Rochereau",
      "Cité Universitaire",
      "Gare de Gentilly",
      "Arcueil - Cachan",
      "Bourg-la-Reine",
      "Sceaux",
      "Fontenay-aux-Roses",
      "Robinson"
    ],
  },
  C: {
    name: "RER C",
    type: "rer",
    description: "La ligne C du RER est la 4e ligne la plus utilisée avec 650 000 voyageurs quotidiens. Ce réseau de 187 km dessert les vallées de la Seine et de la Bièvre, reliant Pontoise à Versailles/Dourdan via Paris avec 84 gares.",
    stations: [
      "Ablon",
      "Arpajon",
      "Athis-Mons",
      "Avenue Foch",
      "Avenue Henri Martin",
      "Avenue du Président Kennedy Maison de Radio France",
      "Bibliothèque François Mitterrand Emile Durkheim",
      "Bièvres",
      "Boulainvilliers",
      "Bouray",
      "Breuillet - Bruyères-le-Châtel",
      "Breuillet Village",
      "Brétigny",
      "Cernay",
      "Chamarande",
      "Champ de Mars Tour Eiffel",
      "Chemin d'Antony",
      "Chilly-Mazarin",
      "Choisy-le-Roi",
      "Dourdan",
      "Dourdan la Forêt",
      "Ermont - Eaubonne",
      "Franconville - Le Plessis-Bouchard",
      "Gare d'Austerlitz",
      "Gennevilliers",
      "Gravigny Balizy",
      "Igny",
      "Invalides",
      "Issy",
      "Issy Val de Seine",
      "Ivry-sur-Seine",
      "Javel",
      "Jouy-en-Josas",
      "La Norville - Saint-Germain-lès-Arpajon",
      "Lardy",
      "Les Ardoines",
      "Les Grésillons",
      "Les Saules",
      "Longjumeau",
      "Marolles-en-Hurepoix",
      "Massy - Palaiseau",
      "Massy - Verrières",
      "Meudon Val Fleury",
      "Montigny - Beauchamp",
      "Musée d'Orsay",
      "Orly Ville",
      "Petit Jouy Les Loges",
      "Petit Vaux",
      "Pierrelaye",
      "Pont de Rungis Aéroport d'Orly",
      "Pont de l'Alma",
      "Pont du Garigliano - Hôpital Européen G. Pompidou",
      "Pontoise",
      "Porchefontaine",
      "Porte Maillot",
      "Porte de Clichy",
      "Péreire",
      "Rungis la Fraternelle",
      "Saint-Chéron",
      "Saint-Cloud",
      "Saint-Cyr",
      "Saint-Gratien",
      "Saint-Martin d'Étampes",
      "Saint-Michel Notre-Dame",
      "Saint-Michel-sur-Orge",
      "Saint-Ouen",
      "Saint-Ouen-l'Aumône",
      "Saint-Ouen-l'Aumône Liesse",
      "Saint-Quentin en Yvelines - Montigny-le-Bretonneux",
      "Sainte-Geneviève-des-Bois",
      "Savigny-sur-Orge",
      "Sermaise",
      "Suresnes Mont Valérien",
      "Vauboyen",
      "Versailles Chantiers",
      "Versailles Château Rive Gauche",
      "Villeneuve-le-Roi",
      "Viroflay Rive Gauche",
      "Vitry-sur-Seine",
      "Égly",
      "Épinay-sur-Orge",
      "Épinay-sur-Seine",
      "Étampe",
      "Étréchy"
    ],
  },

  D: {
    name: "RER D",
    type: "rer",
    description: "La ligne D du RER relie Orry-la-Ville à Melun/Malesherbes sur 197 km. Avec 59 gares et 600 000 voyageurs quotidiens, c'est l'une des lignes les plus longues et fréquentées du réseau francilien.",
    stations: [
      "Ballancourt",
      "Boigneville",
      "Boissise-le-Roi",
      "Boussy-Saint-Antoine",
      "Boutigny",
      "Brunoy",
      "Buno - Gironville",
      "Cesson",
      "Chantilly - Gouvieux",
      "Châtelet les Halles",
      "Combs-la-Ville - Quincy",
      "Corbeil-Essonnes",
      "Creil",
      "Créteil Pompadour",
      "Essonnes Robinson",
      "Gare de Lyon",
      "Gare du Nord",
      "Garges - Sarcelles",
      "Goussainville",
      "Grand Bourg",
      "Grigny Centre",
      "Juvisy",
      "La Borne Blanche",
      "La Ferté-Alais",
      "Le Bras de Fer",
      "Le Coudray-Montceaux",
      "Le Mée",
      "Le Plessis Chenet",
      "Le Vert de Maisons",
      "Les Noues",
      "Lieusaint - Moissy",
      "Louvres",
      "Maisons-Alfort - Alfortville",
      "Maisse",
      "Malesherbes",
      "Melun",
      "Mennecy",
      "Montgeron - Crosne",
      "Moulin Galant",
      "Orangis Bois de l'Épine",
      "Orry-la-Ville - Coye",
      "Pierrefitte - Stains",
      "Ponthierry - Pringy",
      "Ris-Orangis",
      "Saint-Denis",
      "Saint-Fargeau",
      "Savigny-le-Temple - Nandy",
      "Stade de France Saint-Denis",
      "Survilliers - Fosses",
      "Vigneux-sur-Seine",
      "Villabé",
      "Villeneuve Triage",
      "Villeneuve-Saint-Georges",
      "Villiers-le-Bel - Gonesse - Arnouville",
      "Viry-Châtillon",
      "Vosves",
      "Yerres",
      "Évry",
      "Évry - Courcouronnes"
    ],
  },
  E: {
    name: "RER E",
    type: "rer",
    description: "La ligne E du RER (Réseau Express Régional) d’Île-de-France est la ligne la plus courte et la plus récente des 5 lignes du RER qu’empruntent tous les jours les millions de Parisiens et autres touristes pour leurs multiples déplacements en utilisant les moyens de transport en commun.",
    stations: [
      "Bondy",
      "Chelles - Gournay",
      "Gagny",
      "Gare Saint-Lazare",
      "Gretz-Armainvilliers",
      "Le Chénay Gagny",
      "Le Raincy - Villemomble - Montfermeil",
      "Les Boullereaux Champigny",
      "Les Yvris Noisy-le-Grand",
      "Magenta",
      "Nogent - Le Perreux",
      "Noisy-le-Sec",
      "Ozoir-la-Ferrière",
      "Pantin",
      "Roissy-en-Brie",
      "Rosa Parks",
      "Rosny Bois Perrier",
      "Rosny-sous-Bois",
      "Tournan",
      "Val de Fontenay",
      "Villiers-sur-Marne - Le Plessis-Trévise",
      "Émerainville - Pontault-Combault"
    ],
  }
};

export const tramLines = {
  T1: {
    name: "Tram 1",
    type: "tram",
    description: "La ligne de tramway T1 de la RATP est l'une des lignes les plus importantes du réseau de transport en commun de la région parisienne. Elle relie la ville de Noisy-le-Sec, située à l'est de Paris, à la ville d'Asnières-sur-Seine, située au nord de la ville. La ligne de tramway est l'une des plus longues de la RATP, avec une distance de près de 17 kilomètres. Les horaires des prochains passages sont mis à jour en temps réel.",
    stations: [
      "Asnières - Gennevilliers Les Courtilles",
      "Auguste Delaune",
      "Basilique de Saint-Denis",
      "Bobigny Pablo Picasso",
      "Chemin des Reniers",
      "Cimetière de Saint-Denis",
      "Clovis / Drancy - Avenir",
      "Cosmonautes",
      "Danton",
      "Escadrille Normandie - Niémen",
      "Gaston Roulaud",
      "Gennevilliers",
      "Hôpital Avicenne",
      "Hôpital Delafontaine / Joliot Curie",
      "Hôtel de Ville de Bobigny",
      "Hôtel de Ville de la Courneuve",
      "Jean Rostand / Lamartine",
      "L'Ile-Saint-Denis (Mairie)",
      "La Courneuve - 8 Mai 1945",
      "La Courneuve - Six Routes",
      "La Ferme",
      "La Noue",
      "Le Luth",
      "Le Village",
      "Libération",
      "Mairie",
      "Marché de Saint-Denis",
      "Maurice Lachâtre",
      "Noisy-le-Sec",
      "Parc des Chanteraines",
      "Petit Noisy",
      "Pont de Bondy",
      "Quatre Routes",
      "Saint-Denis",
      "Stade Géo André",
      "Théâtre Gérard Philippe / Eglise Neuve",
      "Timbaud"
    ],  
  },
  T2: {
    name: "Tram T2",
    type: "tram",
    description: "La ligne de tramway T2 de la RATP est une ligne clé du réseau de transport en commun de la région parisienne. Elle relie la ville de Bezons, située à l'ouest de Paris, à la Porte de Versailles, dans le sud-ouest de la ville. La ligne T2 est l'une des lignes de tramway les plus fréquentées de la RATP, avec une distance de près de 17 kilomètres et 25 arrêts au total. Les horaires des prochains passages sont mis à jour en temps réel.",
    stations: [
      "Belvédère",
      "Brimborion",
      "Charlebourg",
      "Faubourg de l'Arche",
      "Henri Farman",
      "Issy Val de Seine",
      "Jacqueline Auriol",
      "Jacques-Henri Lartigue",
      "La Défense (Grande Arche)",
      "Les Coteaux",
      "Les Fauvelles",
      "Les Milons",
      "Les Moulineaux",
      "Meudon-sur-Seine",
      "Musée de Sèvres",
      "Parc Pierre Lagravère",
      "Parc de Saint-Cloud",
      "Pont de Bezons",
      "Porte d'Issy",
      "Porte de Versailles",
      "Puteaux",
      "Suresnes - Longchamp",
      "Suzanne Lenglen",
      "Victor Basch"
    ]
  },
  T3a: {
    name: "Tram T3a",
    type: "tram",
    description: "Le T3a est une ligne de tramway de la RATP qui relie la ville de Pont du Garigliano dans le sud-ouest de Paris à la ville de Porte de Vincennes dans l'est de la ville. Inaugurée en 2012, cette ligne de tramway est une extension de la ligne T3. Le T3a est un moyen de transport pratique pour les habitants de l'est de la ville qui souhaitent se rendre rapidement et facilement dans d'autres quartiers. La ligne dessert plusieurs arrêts clés comme la Porte de Charenton et la Bibliothèque François-Mitterrand. Les horaires des prochains passages sont mis à jour en temps réel.",
    stations: [
      "Alexandra David-Néel / Porte de Saint-Mandé",
      "Avenue de France",
      "Balard",
      "Baron Leroy",
      "Brancion",
      "Cité universitaire",
      "Desnouettes",
      "Didot",
      "Georges Brassens",
      "Jean Moulin",
      "Maryse Bastié",
      "Montempoivre",
      "Montsouris",
      "Pont du Garigliano - Hôpital Européen G. Pompidou",
      "Porte Dorée",
      "Porte d'Italie",
      "Porte d'Ivry",
      "Porte d'Orléans",
      "Porte de Charenton",
      "Porte de Choisy",
      "Porte de Vanves",
      "Porte de Versailles",
      "Porte de Vincennes",
      "Poterne des Peupliers",
      "Stade Charléty - Porte de Gentilly"
    ],
  },
  T3b: {
    name: "Tram T3b",
    type: "tram",
    description: "Le tramway T3b est une ligne qui relie la Porte de Vincennes (12ème arrondissement) à la Porte d'Asnières (17ème arrondissement), en passant par les quartiers de Nation, Gambetta, Saint-Fargeau et Porte de la Villette. Inaugurée en décembre 2012, cette ligne mesure environ 14 kilomètres et compte 25 stations. Elle fonctionne tous les jours de 5h30 à 0h30 en semaine (jusqu'à 1h30 les vendredis, samedis et veilles de fêtes). Les horaires des prochains passages sont mis à jour en temps réel.",
    stations: [
      "Adrienne Bolland",
      "Angélique Compoint - Porte de Montmartre",
      "Anna de Noailles",
      "Anny Flore",
      "Butte du Chapeau Rouge",
      "Canal Saint-Denis",
      "Colette Besson",
      "Delphine Seyrig",
      "Diane Arbus - Porte des Poissonniers",
      "Ella Fitzgerald",
      "Epinettes - Pouchet",
      "Honoré De Balzac",
      "Hôpital Robert Debré",
      "Marie De Miribel",
      "Porte Dauphine",
      "Porte Maillot",
      "Porte d'Asnières - Marguerite Long",
      "Porte d'Aubervilliers",
      "Porte de Bagnolet",
      "Porte de Champerret",
      "Porte de Clichy",
      "Porte de Clignancourt",
      "Porte de La Chapelle",
      "Porte de La Villette",
      "Porte de Montreuil",
      "Porte de Pantin",
      "Porte de Saint-Ouen",
      "Porte de Vincennes",
      "Porte des Lilas",
      "Rosa Parks",
      "Square Sainte-Odile",
      "Séverine",
      "Thérèse Pierre"
    ],
  },
  T4: {
    name: "Tram T4",
    type: "tram",
    description: "Le tramway T4 est une ligne de transport en commun en site propre qui relie les villes de Bondy, Aulnay-sous-Bois et Montfermeil en Île-de-France. Inaugurée en novembre 2006, cette ligne de tramway mesure environ 8 kilomètres de longueur et compte 11 stations. Les horaires des prochains passages sont mis à jour en temps réel.",
    stations: [
      "Allée de la Tour-Rendez-vous",
      "Arboretum",
      "Aulnay-sous-Bois",
      "Bondy",
      "Clichy - Montfermeil",
      "Clichy-sous-Bois - Mairie",
      "Freinville Sevran",
      "Gargan",
      "Hôpital Intercommunal / Collège Pablo Picasso",
      "L'Abbaye",
      "Les Coquetiers",
      "Les Pavillons-sous-Bois",
      "Lycée Henri Sellier",
      "Léon Blum",
      "Maurice Audin",
      "Notre-Dame-des-Anges",
      "Remise à Jorelle",
      "Romain Rolland",
      "Rougemont Chanteloup",
      "République - Marx Dormoy"
    ],
  },
  T5: {
    name: "Tram T5",
    type: "tram",
    description: "Le tramway T5 est une ligne de transport en commun en site propre qui relie les villes de Saint-Denis et Garges-lès-Gonesse, en banlieue parisienne. Cette ligne de tramway a été inaugurée en 2013 et mesure environ 6,6 kilomètres de longueur, avec un total de 16 stations. Les horaires des prochains passages sont mis à jour en temps réel.",
    stations: [
      "Alcide d'Orbigny",
      "Baudelaire",
      "Butte Pinson (Parc Régional)",
      "Garges - Sarcelles",
      "Guynemer",
      "Jacques Prévert / Cimetière",
      "Joncherolles",
      "Les Cholettes / Albert Camus",
      "Les Flanades",
      "Lochères",
      "Mairie de Pierrefitte",
      "Marché de Saint-Denis",
      "Paul Valéry",
      "Petit Pierrefitte",
      "Roger Semât",
      "Suzanne Valadon"
    ],
  },
  T6: {
    name: "Tram T6",
    type: "tram",
    description: "Le tram T6 est une ligne de tramway de la RATP qui relie Châtillon-Montrouge à Viroflay, en passant par Clamart, Fontenay-aux-Roses, Sceaux, Antony et Vélizy-Villacoublay. Ouverte en 2014, cette ligne moderne est équipée de rames Citadis de 43 mètres pouvant accueillir 314 passagers. Les horaires des prochains passages sont mis à jour en temps réel.",
    stations: [
      "Centre de Châtillon",
      "Châtillon Montrouge",
      "Dewoitine",
      "Division Leclerc",
      "Georges Millandy / Clinique",
      "Georges Pompidou",
      "Général De Gaulle / Parc André Malraux",
      "Hôpital Béclère",
      "Inovel Parc Nord",
      "L'Onde - Maison des Arts / Ravel",
      "Louvois",
      "Mail de la Plaine",
      "Mairie de Vélizy",
      "Meudon-la-Forêt",
      "Pavé Blanc",
      "Robert Wagner",
      "Soleil Levant",
      "Vauban",
      "Viroflay Rive Droite",
      "Viroflay Rive Gauche",
      "Vélizy 2 (Nord) / Europe Nord"
    ],
  },
  T7: {
    name: "Tram T7",
    type: "tram",
    description: "Le tramway T7 relie Athis-Mons (Essonne) à la station de métro Villejuif - Louis Aragon (Val-de-Marne). Cette ligne entièrement en site propre circule sur une voie dédiée, garantissant une grande régularité de service. Les horaires des prochains passages sont mis à jour en temps réel.",
    stations: [
      "Auguste Perret / Cimetière Parisien de Thiais",
      "Aéroport Orly 4 (Terminal Sud)",
      "Bretagne",
      "Caroline Aigle (Orlyfret)",
      "Coeur d'Orly",
      "Domaine Chérioux",
      "Hélène Boucher (Orlytech)",
      "La Belle Épine",
      "Lamartine",
      "Moulin Vert",
      "Place de la Logistique",
      "Porte de L'Essonne",
      "Porte de Rungis",
      "Porte de Thiais (Marché international)",
      "Robert Schuman / Traversière",
      "Rungis la Fraternelle",
      "Saarinen",
      "Villejuif Louis Aragon"
    ],
  },
  T8: {
    name: "Tram T8",
    type: "tram",
    description: "Le tram T8 est une ligne de tramway située dans la banlieue nord-est de Paris. Cette ligne s'étend sur 8,5 km entre Saint-Denis et Épinay-sur-Seine, avec 17 stations au total. Les horaires des prochains passages sont mis à jour en temps réel.",
    stations: [
      "Blumenthal",
      "César",
      "Delaunay - Belleville",
      "Epinay - Orgemont",
      "Gilbert Bonnemaison",
      "Jean Vilar",
      "Lacépède",
      "Les Béatus",
      "Les Mobiles",
      "Pablo Néruda",
      "Paul Éluard / Théâtre Gérard Philipe",
      "Rose Bertin (Centre Commercial l'Ilo)",
      "Saint-Denis",
      "Saint-Denis Porte de Paris",
      "Square de Geyter",
      "Villetaneuse Université",
      "Épinay-sur-Seine"
    ]
  },
  T9: {
    name: "Tram T9",
    type: "tram",
    description:
      "Le tram T9 de la RATP est une ligne de tramway située dans le sud de la banlieue parisienne. Elle relie la porte de Choisy et Orly sur une distance de 10,3 kilomètres, avec un total de 19 arrêts. Le tram T9 est un mode de transport moderne et confortable, équipé de rames à plancher bas intégral permettant un accès facile pour les personnes à mobilité réduite. Les tramways sont également climatisés pour un voyage agréable, quelle que soit la saison.",
    stations: [
      "Beethoven - Concorde",
      "Camille Groult",
      "Carle - Darthé",
      "Christophe Colomb",
      "Châteaudun - Barbès",
      "Cimetière Parisien d'Ivry",
      "Constant Coquelin",
      "Four - Peary",
      "Germaine Tailleferre",
      "La Briqueterie",
      "Les Saules",
      "Mairie de Vitry-sur-Seine",
      "Musée MAC VAL",
      "Orly - Gaston Viens",
      "Porte de Choisy",
      "Rouget de Lisle",
      "Trois Communes",
      "Verdun - Hoche",
      "Watteau - Rondenay",
    ],
  },
  T11: {
    name: "Tram T11",
    type: "tram",
    description: "Le tramway T11 dessert la banlieue est de Paris, reliant Epinay-sur-Seine au Bourget (avec prolongement prévu vers Noisy-le-Sec) en traversant la Seine-Saint-Denis. Inauguré en 2017 comme prolongement de la ligne T1, il offre une alternative écologique à la voiture. Les horaires des prochains passages sont mis à jour en temps réel.",
    stations: [
      "Dugny - La Courneuve",
      "Le Bourget",
      "Pierrefitte - Stains",
      "Stains la Cerisaie",
      "Villetaneuse Université",
      "Épinay - Villetaneuse",
      "Épinay-sur-Seine"
    ],
  },
  T13: {
    name: "Tram T13",
    type: "tram",
    description:
      "Le Tram T13 est une ligne de tramway située en région parisienne, qui relie la ville de Saint-Cyr-l'Ecole à la ville de Saint-Germain-en-Laye. Longue de près de 19 km, elle dessert 21 stations réparties sur 5 communes, traversant notamment les villes de Versailles et Le Pecq. Le tram T13 fonctionne tous les jours de la semaine, y compris les week-ends et jours fériés, de 5h à 1h du matin environ, avec une fréquence de passage d'environ 10 minutes en heures de pointe et de 15 à 20 minutes en heures creuses.",
    stations: [
      "Allée Royale",
      "Bailly",
      "Camp des Loges",
      "Fourqueux - Bel Air",
      "L'Etang - Les Sablons",
      "Les Portes de Saint-Cyr",
      "Lisière Pereire",
      "Mareil-Marly",
      "Noisy-le-Roi",
      "Saint-Cyr",
      "Saint-Germain-en-Laye",
      "Saint-Nom-la-Bretèche Forêt de Marly",
    ],
  },
};

export const transilienLines = {
  H: {
    name: "Transilien H",
    type: "train",
    description:
      "La ligne H du Transilien est l’une des lignes de transport en commun les plus utilisées par les Franciliens pour se rendre au travail ou pour leurs besoins de déplacements. Elle dessert principalement le Nord-Ouest de l’Île-de-France, notamment le Val-d’Oise. Elle a plusieurs branches reliant Paris-Nord à Luzarches, Pontoise et Persan-Beaumont. Mise en service depuis 1846, elle a été modernisée en 2001. Exploitée par la SNCF en accord avec Île-de-France Mobilités.",
    stations: [
      "Auvers-sur-Oise", "Belloy - Saint-Martin", "Bessancourt", "Boran-sur-Oise", "Bouffémont - Moisselles",
      "Bruyères-sur-Oise", "Cernay", "Champ de Courses d'Enghien", "Champagne-sur-Oise", "Chaponval", "Creil",
      "Deuil - Montmagny", "Domont", "Enghien-les-Bains", "Epluches", "Ermont - Eaubonne", "Ermont Halte",
      "Franconville - Le Plessis-Bouchard", "Frépillon", "Gare du Nord", "Gros Noyer Saint-Prix", "Groslay",
      "L'Isle-Adam - Parmain", "La Barre Ormesson", "Luzarches", "Montigny - Beauchamp", "Montsoult - Maffliers",
      "Mériel", "Méry-sur-Oise", "Nointel - Mours", "Persan - Beaumont", "Pierrelaye", "Pont Petit", "Pontoise",
      "Presles - Courcelles", "Précy-sur-Oise", "Saint-Denis", "Saint-Leu-d'Esserent", "Saint-Leu-la-Forêt",
      "Saint-Ouen-l'Aumône", "Saint-Ouen-l'Aumône Liesse", "Sarcelles - Saint-Brice", "Seugy", "Taverny",
      "Valmondois", "Vaucelles", "Viarmes", "Villaines", "Écouen - Ézanville", "Épinay - Villetaneuse"
    ],
  },
  J: {
    name: "Transilien J",
    type: "train",
    description:
      "La ligne J du Transilien dessert principalement l’ouest de l’Île-de-France. C’est l’une des lignes les plus fréquentées, utilisée aussi bien par les travailleurs que les touristes. Mise en circulation dès 1837, sa configuration actuelle date de 2004. Elle couvre 256 km, dessert 52 gares et 75 communes.",
    stations: [
      "Andrésy", "Argenteuil", "Asnières-sur-Seine", "Aubergenville Élisabethville", "Bois-Colombes", "Boissy-l'Aillerie",
      "Chanteloup-les-Vignes", "Chars", "Chaumont-en-Vexin", "Colombes", "Conflans Fin d'Oise", "Conflans Sainte-Honorine",
      "Cormeilles-en-Parisis", "Ermont - Eaubonne", "Gare Saint-Lazare", "Gargenville", "Gisors", "Herblay",
      "Houilles - Carrières-sur-Seine", "Issou - Porcheville", "Juziers", "La Frette - Montigny", "Lavilletertre",
      "Le Stade", "Les Clairières de Verneuil", "Les Mureaux", "Liancourt-Saint-Pierre", "Limay", "Mantes Station",
      "Mantes-la-Jolie", "Maurecourt", "Meulan - Hardricourt", "Montgeroult - Courcelles", "Osny", "Poissy", "Pontoise",
      "Saint-Ouen-l'Aumône Quartier de l'Église", "Sannois", "Santeuil - Le Perchay", "Thun le Paradis", "Trie-Château",
      "Triel-sur-Seine", "Us", "Val d'Argenteuil", "Vaux-sur-Seine", "Vernouillet - Verneuil", "Villennes-sur-Seine",
      "Épône - Mézières", "Éragny - Neuville"
    ],
  },
  K: {
    name: "Transilien K",
    type: "train",
    description:
      "La ligne K du Transilien dessert le nord-est de l’Île-de-France. Elle relie la gare du Nord à Crépy-en-Valois. C’est la plus courte des lignes Transilien (61 km). Mise en service dans les années 1860, son format actuel date de 2004. Elle dessert 10 gares et 13 communes.",
    stations: [
      "Aulnay-sous-Bois", "Compans", "Crépy-en-Valois", "Dammartin - Juilly - Saint-Mard", "Gare du Nord",
      "Le Plessis-Belleville", "Mitry - Claye", "Nanteuil-le-Haudouin", "Ormoy-Villers", "Thieux - Nantouillet"
    ],
  },
  L: {
    name: "Transilien L",
    type: "train",
    description:
      "La ligne L dessert l’ouest de l’Île-de-France et est intégralement située dans la région. Elle comporte plusieurs branches. Exploitée par la SNCF en partenariat avec Île-de-France Mobilités, elle transporte environ 350 000 voyageurs par jour.",
    stations: [
      "Achères Ville", "Asnières-sur-Seine", "Bougival", "Bécon les Bruyères", "Cergy Préfecture",
      "Cergy Saint-Christophe", "Cergy le Haut", "Chaville Rive Droite", "Clichy - Levallois", "Conflans Fin d'Oise",
      "Courbevoie", "Garches - Marnes-la-Coquette", "Gare Saint-Lazare", "Houilles - Carrières-sur-Seine",
      "L'Étang-la-Ville", "La Celle-Saint-Cloud", "La Défense (Grande Arche)", "La Garenne-Colombes", "Le Val d'Or",
      "Les Vallées", "Louveciennes", "Maisons-Laffitte", "Montesson - Mareil-Marly", "Nanterre - Ville",
      "Puteaux", "Rueil-Malmaison", "Saint-Nom-la-Bretèche Forêt de Marly", "Suresnes - Mont-Valérien",
      "Vaucresson", "Versailles Rive Droite", "Villennes-sur-Seine", "Viroflay Rive Gauche"
    ],
  },
};
const linesData = {
  metroLines,
  rerLines,
  tramLines,
  transilienLines,
};
export default linesData;
